### PR TITLE
Reformatting and migration to AndroidX

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Deleted generated/redundant files
- Target Android Pie
- Updated Android Studio (3.1.4 to 3.3.2), Gradle (4.4 to 5.3), and Kotlin (1.2.60 to 1.3.21)
- Kotlin jdk7 to jdk8
- Set compilation of Java to 1.8 (just a config thing, because default is 1.7 but we should use 1.8)
- Renamed thunder.ogg to storm.ogg to match code
- Reformatted code in general (and xml files)
- Renamed vals to lowercase so Kotlin doesn't flip shit
- Migrated to AndroidX

### CODE REVIEW

**Comment by ianmcxa** [comment]
Thanks for the pull request. I'll try to review and merge this week.

**Comment by TacoTheDank** [comment]
👍

**Comment by ianmcxa** [comment]
Yeah, I wanna add the timer feature first tho.

**Comment by TacoTheDank** [comment]
Ok

**Pull request merged**
